export const EMOJI_CATEGORIES = [
  {
    id: "smileys",
    title: "Smileys & People",
    items: [
      { char: "😀", name: "grinning face" },
      { char: "😃", name: "grinning face (big eyes)" },
      { char: "😄", name: "grinning face (smiling eyes)" },
      { char: "😁", name: "beaming face" },
      { char: "😆", name: "grinning squinting" },
      { char: "😅", name: "grinning with sweat" },
      { char: "😂", name: "face with tears" },
      { char: "🤣", name: "rolling on floor laughing" },
      { char: "🙂", name: "slightly smiling" },
      { char: "🙃", name: "upside-down face" },
      { char: "😉", name: "winking face" },
      { char: "😊", name: "smiling face" },
      { char: "😇", name: "smiling with halo" },
      { char: "🥰", name: "smiling with hearts" },
      { char: "😍", name: "heart eyes" },
      { char: "🤩", name: "star-struck" },
      { char: "😘", name: "blowing a kiss" },
      { char: "😗", name: "kissing face" },
      { char: "☺️", name: "smiling (soft)" },
      { char: "😋", name: "savoring food" },
      { char: "😛", name: "tongue out" },
      { char: "😜", name: "winking tongue" },
      { char: "🤪", name: "zany face" },
      { char: "🤨", name: "raised eyebrow" },
      { char: "🧐", name: "monocle face" },
      { char: "🤓", name: "nerd face" },

      { char: "👋", name: "waving hand" },
      { char: "🤚", name: "raised back hand" },
      { char: "🖐️", name: "hand with fingers splayed" },
      { char: "✋", name: "raised hand" },
      { char: "🖖", name: "vulcan salute" },
      { char: "👌", name: "OK hand" },
      { char: "🤏", name: "pinching hand" },
      { char: "✌️", name: "victory hand" },
      { char: "🤞", name: "crossed fingers" },
      { char: "🤟", name: "love-you gesture" },
      { char: "🤘", name: "sign of the horns" },
      { char: "🤙", name: "call me hand" },
      { char: "👈", name: "pointing left" },
      { char: "👉", name: "pointing right" },
      { char: "👆", name: "pointing up" },
      { char: "👇", name: "pointing down" },
      { char: "👍", name: "thumbs up" },
      { char: "👎", name: "thumbs down" },
      { char: "👏", name: "clapping hands" },
      { char: "🙌", name: "raising hands" },
      { char: "👐", name: "open hands" },
      { char: "🤲", name: "palms up together" },

      { char: "👶", name: "baby" },
      { char: "🧒", name: "child" },
      { char: "👦", name: "boy" },
      { char: "👧", name: "girl" },
      { char: "🧑", name: "person" },
      { char: "👨", name: "man" },
      { char: "👩", name: "woman" },
      { char: "👴", name: "old man" },
      { char: "👵", name: "old woman" },
      { char: "🧓", name: "older adult" },
      { char: "🧔", name: "bearded person" },
      { char: "👱‍♂️", name: "man with blond hair" },
      { char: "👱‍♀️", name: "woman with blond hair" },
      { char: "👮‍♂️", name: "police officer" },
      { char: "👩‍⚕️", name: "health worker (woman)" },
      { char: "👨‍⚕️", name: "health worker (man)" },
      { char: "👩‍🏫", name: "teacher (woman)" },
      { char: "👨‍🏫", name: "teacher (man)" },
      { char: "👩‍🍳", name: "cook (woman)" },
      { char: "👨‍🍳", name: "cook (man)" }
    ]
  },
  {
    id: "hearts",
    title: "Hearts & Emotion",
    items: [
      { char: "❤️", name: "red heart" },
      { char: "🧡", name: "orange heart" },
      { char: "💛", name: "yellow heart" },
      { char: "💚", name: "green heart" },
      { char: "💙", name: "blue heart" },
      { char: "💜", name: "purple heart" },
      { char: "🖤", name: "black heart" },
      { char: "🤍", name: "white heart" },
      { char: "💔", name: "broken heart" },
      { char: "💕", name: "two hearts" },
      { char: "💞", name: "revolving hearts" },
      { char: "💓", name: "beating heart" },
      { char: "💗", name: "growing heart" },
      { char: "💖", name: "sparkling heart" },
      { char: "✨", name: "sparkles" },
      { char: "⭐", name: "star" },
      { char: "🌟", name: "glowing star" },
      { char: "🔥", name: "fire" },
      { char: "💫", name: "dizzy" }
    ]
  },
  {
    id: "animals",
    title: "Animals & Nature",
    items: [
      { char: "🐶", name: "dog" },
      { char: "🐱", name: "cat" },
      { char: "🐭", name: "mouse" },
      { char: "🐹", name: "hamster" },
      { char: "🐰", name: "rabbit" },
      { char: "🦊", name: "fox" },
      { char: "🐻", name: "bear" },
      { char: "🐼", name: "panda" },
      { char: "🐨", name: "koala" },
      { char: "🐯", name: "tiger" },
      { char: "🦁", name: "lion" },
      { char: "🐮", name: "cow" },
      { char: "🐷", name: "pig" },
      { char: "🐸", name: "frog" },
      { char: "🐵", name: "monkey" },
      { char: "🙈", name: "see-no-evil monkey" },
      { char: "🙉", name: "hear-no-evil monkey" },
      { char: "🙊", name: "speak-no-evil monkey" },
      { char: "🐒", name: "monkey face" },
      { char: "🐔", name: "chicken" },
      { char: "🐧", name: "penguin" },
      { char: "🐦", name: "bird" },
      { char: "🐤", name: "baby chick" },
      { char: "🦆", name: "duck" },
      { char: "🦅", name: "eagle" },
      { char: "🦉", name: "owl" },
      { char: "🦇", name: "bat" },
      { char: "🐺", name: "wolf" },
      { char: "🐗", name: "boar" },
      { char: "🐴", name: "horse" },
      { char: "🦄", name: "unicorn" },
      { char: "🐝", name: "bee" },
      { char: "🐛", name: "bug" },
      { char: "🦋", name: "butterfly" },
      { char: "🐌", name: "snail" },
      { char: "🐞", name: "lady beetle" },
      { char: "🐜", name: "ant" },
      { char: "🪲", name: "beetle" },
      { char: "🪳", name: "cockroach" },
      { char: "🦟", name: "mosquito" },
      { char: "🦠", name: "microbe" },
      { char: "🌸", name: "cherry blossom" },
      { char: "🌼", name: "blossom" },
      { char: "🌻", name: "sunflower" },
      { char: "🌷", name: "tulip" },
      { char: "🌹", name: "rose" },
      { char: "🥀", name: "wilted flower" },
      { char: "🌱", name: "seedling" },
      { char: "🌲", name: "evergreen tree" },
      { char: "🌳", name: "deciduous tree" }
    ]
  },
  {
    id: "food",
    title: "Food & Drink",
    items: [
      { char: "🍏", name: "green apple" },
      { char: "🍎", name: "red apple" },
      { char: "🍐", name: "pear" },
      { char: "🍊", name: "orange" },
      { char: "🍋", name: "lemon" },
      { char: "🍌", name: "banana" },
      { char: "🍉", name: "watermelon" },
      { char: "🍇", name: "grapes" },
      { char: "🍓", name: "strawberry" },
      { char: "🍈", name: "melon" },
      { char: "🍒", name: "cherries" },
      { char: "🍑", name: "peach" },
      { char: "🥭", name: "mango" },
      { char: "🍍", name: "pineapple" },
      { char: "🥥", name: "coconut" },
      { char: "🥝", name: "kiwi" },
      { char: "🍅", name: "tomato" },
      { char: "🍆", name: "eggplant" },
      { char: "🥑", name: "avocado" },
      { char: "🥦", name: "broccoli" },
      { char: "🥕", name: "carrot" },
      { char: "🌽", name: "corn" },
      { char: "🌶️", name: "hot pepper" },
      { char: "🥒", name: "cucumber" },
      { char: "🥬", name: "leafy green" },
      { char: "🥯", name: "bagel" },
      { char: "🍞", name: "bread" },
      { char: "🥐", name: "croissant" },
      { char: "🥖", name: "baguette" },
      { char: "🥨", name: "pretzel" },
      { char: "🥞", name: "pancakes" },
      { char: "🧇", name: "waffle" },
      { char: "🧀", name: "cheese" },
      { char: "🍗", name: "poultry leg" },
      { char: "🍖", name: "meat on bone" },
      { char: "🍕", name: "pizza" },
      { char: "🌭", name: "hot dog" },
      { char: "🍔", name: "hamburger" },
      { char: "🍟", name: "fries" },
      { char: "🥪", name: "sandwich" },
      { char: "🌮", name: "taco" },
      { char: "🌯", name: "burrito" },
      { char: "🥙", name: "stuffed flatbread" },
      { char: "🥗", name: "salad" },
      { char: "🍿", name: "popcorn" },
      { char: "🧂", name: "salt" },
      { char: "🥫", name: "canned food" },
      { char: "🍱", name: "bento box" },
      { char: "🍛", name: "curry rice" },
      { char: "🍣", name: "sushi" },
      { char: "🍜", name: "steaming bowl" },
      { char: "🍲", name: "pot of food" },
      { char: "🍩", name: "doughnut" },
      { char: "🍪", name: "cookie" },
      { char: "🎂", name: "birthday cake" },
      { char: "🍰", name: "cake" },
      { char: "🧁", name: "cupcake" },
      { char: "🍫", name: "chocolate" },
      { char: "🍬", name: "candy" },
      { char: "🍭", name: "lollipop" },
      { char: "☕", name: "hot beverage" },
      { char: "🍵", name: "tea" },
      { char: "🧃", name: "juice box" },
      { char: "🥤", name: "cup with straw" },
      { char: "🍺", name: "beer mug" },
      { char: "🍻", name: "cheers" },
      { char: "🍷", name: "wine glass" },
      { char: "🥂", name: "clinking glasses" },
      { char: "🍾", name: "bottle with popping cork" },
      { char: "🥃", name: "tumbler glass" },
      { char: "🥡", name: "takeout box" }
    ]
  },
  {
    id: "travel",
    title: "Travel & Places",
    items: [
      { char: "🚗", name: "car" },
      { char: "🚕", name: "taxi" },
      { char: "🚙", name: "SUV" },
      { char: "🚌", name: "bus" },
      { char: "🚎", name: "trolleybus" },
      { char: "🏎️", name: "race car" },
      { char: "🚓", name: "police car" },
      { char: "🚑", name: "ambulance" },
      { char: "🚒", name: "fire truck" },
      { char: "🚐", name: "minivan" },
      { char: "🚚", name: "delivery truck" },
      { char: "🚛", name: "articulated lorry" },
      { char: "🚜", name: "tractor" },
      { char: "🛴", name: "kick scooter" },
      { char: "🚲", name: "bicycle" },
      { char: "🛵", name: "motor scooter" },
      { char: "🏍️", name: "motorcycle" },
      { char: "✈️", name: "airplane" },
      { char: "🛩️", name: "small airplane" },
      { char: "🛰️", name: "satellite" },
      { char: "🚀", name: "rocket" },
      { char: "🛸", name: "flying saucer" },
      { char: "🚁", name: "helicopter" },
      { char: "⛵", name: "sailboat" },
      { char: "🛳️", name: "passenger ship" },
      { char: "🚢", name: "ship" }
    ]
  },
  {
    id: "activities",
    title: "Activities & Objects",
    items: [
      { char: "⚽", name: "soccer ball" },
      { char: "🏀", name: "basketball" },
      { char: "🏈", name: "football" },
      { char: "⚾", name: "baseball" },
      { char: "🎾", name: "tennis" },
      { char: "🏐", name: "volleyball" },
      { char: "🏉", name: "rugby" },
      { char: "🎱", name: "billiards" },
      { char: "🥊", name: "boxing glove" },
      { char: "🥋", name: "martial arts uniform" },
      { char: "🏓", name: "table tennis" },
      { char: "🏸", name: "badminton" },
      { char: "🎣", name: "fishing pole" },
      { char: "🏹", name: "bow and arrow" },
      { char: "🛝", name: "playground slide" },
      { char: "🎮", name: "video game" },
      { char: "🧩", name: "puzzle piece" },
      { char: "🎲", name: "game die" },
      { char: "🎯", name: "dart" },
      { char: "🎳", name: "bowling" },
      { char: "🎻", name: "violin" },
      { char: "🎸", name: "guitar" },
      { char: "🎺", name: "trumpet" },
      { char: "🎷", name: "saxophone" },
      { char: "🎹", name: "piano keyboard" },
      { char: "🎼", name: "musical score" },

      { char: "📱", name: "mobile phone" },
      { char: "💻", name: "laptop" },
      { char: "⌚", name: "watch" },
      { char: "📷", name: "camera" },
      { char: "🎥", name: "movie camera" },
      { char: "📺", name: "television" },
      { char: "📻", name: "radio" },
      { char: "🧭", name: "compass" },
      { char: "🔦", name: "flashlight" },
      { char: "💡", name: "light bulb" },
      { char: "🔌", name: "plug" },
      { char: "🔋", name: "battery" },
      { char: "🔑", name: "key" },
      { char: "🧰", name: "toolbox" },
      { char: "🔧", name: "wrench" },
      { char: "🔨", name: "hammer" },
      { char: "🧲", name: "magnet" },
      { char: "🧪", name: "test tube" },
      { char: "🔬", name: "microscope" },
      { char: "🔭", name: "telescope" },
      { char: "📡", name: "satellite antenna" },
      { char: "💸", name: "money with wings" },
      { char: "💰", name: "money bag" },
      { char: "💳", name: "credit card" },
      { char: "💎", name: "gem stone" }
    ]
  },
  {
    id: "symbols",
    title: "Symbols & Flags",
    items: [
      { char: "✅", name: "check mark" },
      { char: "✔️", name: "check" },
      { char: "✖️", name: "multiplication" },
      { char: "❌", name: "cross mark" },
      { char: "⭕", name: "hollow red circle" },
      { char: "🔴", name: "red circle" },
      { char: "🟠", name: "orange circle" },
      { char: "🟡", name: "yellow circle" },
      { char: "🟢", name: "green circle" },
      { char: "🔵", name: "blue circle" },
      { char: "🟣", name: "purple circle" },
      { char: "⚫", name: "black circle" },
      { char: "⚪", name: "white circle" },
      { char: "🔺", name: "red triangle" },
      { char: "🔻", name: "down triangle" },
      { char: "🔸", name: "small orange diamond" },
      { char: "🔹", name: "small blue diamond" },
      { char: "💠", name: "diamond with dot" },
      { char: "♻️", name: "recycling symbol" },
      { char: "⚠️", name: "warning" },
      { char: "🚫", name: "prohibited" },
      { char: "❗", name: "exclamation" },
      { char: "❓", name: "question" },
      { char: "🏳️", name: "white flag" },
      { char: "🏴", name: "black flag" },
      { char: "🏁", name: "chequered flag" },
      { char: "🚩", name: "triangular flag" },
      { char: "🇺🇸", name: "flag: US" },
      { char: "🇬🇧", name: "flag: UK" },
      { char: "🇨🇦", name: "flag: Canada" },
      { char: "🇦🇺", name: "flag: Australia" },
      { char: "🇯🇵", name: "flag: Japan" },
      { char: "🇨🇳", name: "flag: China" },
      { char: "🇫🇷", name: "flag: France" },
      { char: "🇩🇪", name: "flag: Germany" },
      { char: "🇮🇳", name: "flag: India" },
      { char: "🇰🇷", name: "flag: Korea" },
      { char: "🇧🇷", name: "flag: Brazil" },
      { char: "🇿🇦", name: "flag: South Africa" },
      { char: "🇪🇺", name: "flag: EU" }
    ]
  },
  {
    id: "weather",
    title: "Weather & Climate",
    items: [
      { char: "☀️", name: "sun" },
      { char: "🌤️", name: "sun behind small cloud" },
      { char: "🌥️", name: "sun behind large cloud" },
      { char: "🌦️", name: "sun behind rain cloud" },
      { char: "🌧️", name: "cloud with rain" },
      { char: "🌨️", name: "cloud with snow" },
      { char: "🌩️", name: "cloud with lightning" },
      { char: "❄️", name: "snowflake" },
      { char: "⛄", name: "snowman" },
      { char: "🌪️", name: "tornado" },
      { char: "🌫️", name: "fog" },
      { char: "🌬️", name: "wind face" },
      { char: "🌊", name: "water wave" },
      { char: "🌈", name: "rainbow" }
    ]
  },
  {
    id: "technology",
    title: "Technology & Devices",
    items: [
      { char: "📟", name: "pager" },
      { char: "📠", name: "fax machine" },
      { char: "🖥️", name: "desktop computer" },
      { char: "🖨️", name: "printer" },
      { char: "🖱️", name: "computer mouse" },
      { char: "🖲️", name: "trackball" },
      { char: "🎤", name: "microphone" },
      { char: "🎧", name: "headphones" },
      { char: "📼", name: "videocassette" },
      { char: "💽", name: "minidisc" },
      { char: "💾", name: "floppy disk" },
      { char: "📀", name: "optical disc" },
      { char: "🗝️", name: "old key" },
      { char: "🔐", name: "locked with key" },
      { char: "🔒", name: "locked" },
      { char: "🔓", name: "unlocked" },
      { char: "🔏", name: "lock with pen" },
      { char: "🔑", name: "key" }
    ]
  }
];


